version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor:
      name: android/android
      tag: '2023.09.1'
    steps:
      - checkout
      
      - run:
          name: Set Java 17
          command: |
            sudo update-alternatives --set java /usr/local/openjdk-17/bin/java
            sudo update-alternatives --set javac /usr/local/openjdk-17/bin/javac
      
      - run:
          name: Verify Java Version
          command: java -version

      - restore_cache:
          key: android-orb-v1-
      
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      
      - run:
          name: Run Build
          command: ./gradlew build
      
      - store_artifacts:
          path: app/build/reports
          destination: reports
      
      - run:
          name: Run Tests
          command: ./gradlew lint test
      
      - store_test_results:
          path: app/build/test-results
      
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file
